# .github/actions/clone_and_compress/action.yml
name: Clone and Compress Repo
description: Clone a private repository and compress it into a tar.gz file
inputs:
  ssh_private_key:
    description: 'SSH Private Key for SSH access'
    required: true
  deploy_key:
    description: 'Deploy key for cloning the repository'
    required: true
  commit_id:
    description: 'commit id to cover default branch'
    required: false
runs:
  using: "composite"
  steps:
    - name: Ensure .ssh directory exists
      shell: bash  # Add shell
      run: |
        mkdir -p ~/.ssh
        echo "${{ inputs.ssh_private_key }}" > ~/.ssh/local_test.pem
        chmod 400 ~/.ssh/local_test.pem  

    - name: Setup SSH
      shell: bash  # Add shell
      run: |
        mkdir -p ~/.ssh
        echo "${{ inputs.deploy_key }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
    - name: Get current commit ID
      shell: bash
      run: |
        echo "Current commit ID is: $GITHUB_SHA"
    - name: Print and store current branch
      shell: bash
      run: |
        if [ -n "$GITHUB_HEAD_REF" ]; then
          branch_name="$GITHUB_HEAD_REF"
        else
          branch_name="${GITHUB_REF##*/}"
        fi
        echo "Current branch: $branch_name"
        echo "BRANCH_NAME=$branch_name" >> $GITHUB_ENV
    - name: Clone the private repository
      shell: bash  # Add shell
      run: |
        echo "Cloning chukonu repository on branch $BRANCH_NAME"
        git clone --branch $BRANCH_NAME  --recurse-submodules git@github.com:chukonu-team/chukonu.git chukonu
        cd chukonu
        if [ -n "${{ inputs.commit_id }}" ]; then
          echo "Checking out to commit ID ${{ inputs.commit_id }}"
          git checkout "${{ inputs.commit_id }}"
        else
          echo "Using the latest commit on branch $BRANCH_NAME"
        fi
    - name: Compress the cloned repository into a tar.gz file
      shell: bash  # Add shell
      run: |
        tar -czf ./ansible/files/chukonu.tar.gz -C ./ chukonu