name: Set up Python and Install Dependencies
description: Sets up Python environment and installs Boto3

runs:
  using: 'composite'
  steps:
    - name: Create directory on master
      run: |
        MASTER_DNS=${{ steps.extract_nodes.outputs.master_dns }}
        ssh -i ~/.ssh/local_test.pem ubuntu@$MASTER_DNS 'mkdir -p /home/ubuntu/tests'
        scp -i ~/.ssh/local_test.pem ./tests/case0.py ubuntu@${MASTER_DNS}:/home/ubuntu/tests/case0.py
      shell: bash  # 添加 shell 指定属性

    # Step 15: 测试
    - name: Run Spark Test
      run: |
        MASTER_DNS=${{ steps.extract_nodes.outputs.master_dns }}
        ssh -i ~/.ssh/local_test.pem ubuntu@$MASTER_DNS \
        "export SPARK_HOME=/usr/local/spark; export PATH=\$PATH:\$SPARK_HOME/bin; spark-submit --master spark://$MASTER_DNS:7077 ~/tests/case0.py"
      shell: bash  # 添加 shell 指定属性