name: Deploy EC2 Instances
description: Creates and manages EC2 instances
inputs:
  aws-access-key-id:
    description: 'SSH Private Key for SSH access'
    required: true
  aws-secret-access-key:
    description: 'Deploy key for cloning the repository'
    required: true
  num-instances:
    description: 'number of instances'
    required: true
  region:
    required: true
  instance-type:
    required: true
  instance-zone:
    required: true
  ami:
    required: true
  key-pair:
    required: true
  security-group-id:
    required: true
  subnet-id:
    required: true
  use-nvme:
    required: true
  run-type:
    required: true
  run-number:
    required: true
runs:
  using: 'composite'
  steps:
    # Step 1: 配置 AWS 凭据
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: us-west-1
    # Step 2. 创建aws集群
    - name: Launch EC2 instances
      run: |
        python ./.github/scripts/create_ec2_instances.py --num-instances ${{ inputs.num-instances }} --region ${{ inputs.region }} \
         --instance-type ${{ inputs.instance-type }} --instance-zone ${{ inputs.instance-zone }} --ami ${{ inputs.ami }} \
         --key-pair ${{ inputs.key-pair }} --security-group-id ${{ inputs.security-group-id }} \
         --subnet-id ${{ inputs.subnet-id }} --use-nvme ${{ inputs.use-nvme }} \
         --run-number ${{ inputs.run-number }} --run-type ${{ inputs.run-type }}
      shell: bash  # 添加 shell 指定属性

    # Step 3. 获取各个节点dns和ip，并存入文件
    - name: Wait for EC2 instances
      run: |
        python ./.github/scripts/get_instance_dns.py  --region ${{ inputs.region }} \
         --run-number ${{ inputs.run-number }} --run-type ${{ inputs.run-type }}
      shell: bash  # 添加 shell 指定属性

    # Step 4: 根据./.github/scripts/nodes_info.txt 生成动态 inventory.ini 文件
    - name: Generate inventory.ini
      run: |
        python ./.github/scripts/generate_inventory.py
      shell: bash  # 添加 shell 指定属性