name: Deploy EC2 Instances
description: Creates and manages EC2 instances

runs:
  using: 'composite'
  steps:
    # Step 1. 创建aws集群
    - name: Launch EC2 instances
      run: |
        python ./scripts/create_ec2_instances.py
      shell: bash  # 添加 shell 指定属性

    # Step 2. 获取各个节点dns和ip，并存入文件
    - name: Wait for EC2 instances
      run: |
        python ./scripts/get_instance_dns.py
      shell: bash  # 添加 shell 指定属性

    # Step 3: 根据./scripts/nodes_info.txt 生成动态 inventory.ini 文件
    - name: Generate inventory.ini
      run: |
        python ./scripts/generate_inventory.py  # 根据实例信息生成 inventory.ini 文件
      shell: bash  # 添加 shell 指定属性