name: Set up Python and Install Dependencies
description: Sets up Python environment and installs Boto3

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Boto3
      run: |
        python -m pip install --upgrade pip
        pip install boto3
      shell: bash  # 添加 shell 指定属性