---
- name: copy chukonu repo
  hosts: master
  become: yes
  tasks:
    - name: Copy chukonu
      copy:
        src: "/root/chukonu.tar.gz"  # Source file on the worker node
        dest: "/root/chukonu.tar.gz"  # Destination on the master node
      loop:
        - chukonu.tar.gz

    - name: Extract chukonu.tar.gz
      unarchive:
        src: "/root/chukonu.tar.gz"   # Source tar.gz file
        dest: "/root/chukonu"         # Destination directory to extract files
        remote_src: yes                # Indicates that the source is on the remote machine

    - name: Cleanup the tar.gz file
      file:
        path: "/root/chukonu.tar.gz"
        state: absent  