---
- name: Install SBT
  hosts: all
  become: yes
  tasks:
    - name: Download sbt from S3
      aws_s3:
        bucket: "zzbuckent"  # 替换为你的 S3 bucket 名称
        object: "sbt-1.10.1.tgz"  # S3 中的 SBT 包
        region: "cn-northwest-1"  # 替换为你的 S3 区域
        dest: "/opt/sbt-1.10.1.tgz"  # 下载路径
        mode: get
      when: "'master' in group_names"
    - name: Extract SBT
      unarchive:
        src: /opt/sbt-1.10.1.tgz
        dest: /opt
        remote_src: yes
      when: "'master' in group_names"
    - name: Remove the downloaded tar file
      file:
        path: /opt/sbt-1.10.1.tgz
        state: absent
      when: "'master' in group_names"
    - name: Create symlink for sbt
      file:
        src: /opt/sbt/bin/sbt  # 确保路径正确
        dest: /usr/local/bin/sbt
        state: link
      when: "'master' in group_names"
    - name: Ensure sbt is executable
      file:
        path: /usr/local/bin/sbt
        mode: '0755'
      when: "'master' in group_names"
    - name: Check SBT version
      command: sbt --version
      register: sbt_version
      when: "'master' in group_names"
    - name: Display SBT version
      debug:
        var: sbt_version.stdout
      when: "'master' in group_names"