- hosts: localhost
  become: yes
  tasks:
    - name: Install necessary software on host
      apt:
        name:
          - tmux
          - unzip
          - git
          - byacc
          - flex
          - bison
          - locales
          - tzdata
          - ccache
          - cmake
          - ninja-build
          - build-essential
          - llvm-11-dev
          - clang-11
          - libiberty-dev
          - libdwarf-dev
          - libre2-dev
          - libz-dev
          - libssl-dev
          - libboost-all-dev
          - libcurl4-openssl-dev
          - openjdk-11-jdk
          - maven
          - libtbb-dev
          - libjemalloc-dev
          - libspdlog-dev
          - g++-10
          - libmsgsl-dev
          - libgtest-dev
          - nfs-common
          - nfs-kernel-server
          - pkg-config
        state: present
      register: install_result
      retries: 3
      delay: 15
      until: install_result.failed == false  # 检查任务是否成功

- hosts: all
  become: yes
  tasks:
    - name: Copy necessary binaries from host to each node
      synchronize:
        src: /usr/bin/  # 只复制可执行文件
        dest: /usr/bin/
        recursive: yes
        delete: no

    - name: Copy necessary libraries from host to each node
      synchronize:
        src: /usr/lib/  # 只复制库文件
        dest: /usr/lib/
        recursive: yes
        delete: no

    - name: Copy necessary include files from host to each node
      synchronize:
        src: /usr/include/  # 复制头文件
        dest: /usr/include/
        recursive: yes
        delete: no

    - name: Update shared libraries cache on nodes
      command: ldconfig