---
- name: install chukonu
  hosts: master
  become: yes
  tasks:
    - name: Copy chukonu
      copy:
        src: ./{{ item }}
        dest: /root/{{ item }}
        owner: root
        mode: '0644'
      loop:
        - chukonu.tar.gz

    - name: Extract chukonu.tar.gz
      unarchive:
        src: "/root/chukonu.tar.gz"   # Source tar.gz file
        dest: "/opt"                  # Destination directory to extract files
        remote_src: yes               # Indicates that the source is on the remote machine
      become: yes
      become_user: root
    - name: Cleanup the tar.gz file
      file:
        path: "/root/chukonu.tar.gz"
        state: absent  
      become: yes
      become_user: root

    - name: Set g++ alternatives
      command: >
        update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-10 10
      ignore_errors: yes

    - name: Set g++ alternatives for g++-9
      command: >
        update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 10
      ignore_errors: yes

    - name: Set g++ to g++-10
      command: update-alternatives --set g++ /usr/bin/g++-10

    - name: Verify g++ version
      command: g++ --version
      register: gpp_version

    - name: Build Chukonu by sbt assembly
      command: sbt assembly
      args:
        chdir: /opt/chukonu/scala

    - name: Run cmake build
      ansible.builtin.command:
        cmd: cmake -DCMAKE_BUILD_TYPE=Release -DCMR_BUILD_APPLICATIONS=OFF -DCMR_BUILD_BB=OFF -DCMR_BUILD_EXAMPLES=OFF -DCMR_BUILD_MICROBENCHMARK=OFF -DCMR_BUILD_TESTS=OFF -DCMR_BUILD_TOOLS=OFF -DCMR_BUILD_TPCDS=OFF -DCMAKE_INSTALL_PREFIX=/opt/chukonu_install ..
        chdir: /opt/chukonu/build
      environment:
        CC: gcc
        CXX: g++
        JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
      become: true
    - name: Build Chukonu
      command: make -j8
      args:
        chdir: /opt/chukonu/build

    - name: Package Scala project
      command: sbt +package
      args:
        chdir: /opt/chukonu/scala

    - name: Install Chukonu
      command: make install
      args:
        chdir: /opt/chukonu/build

    - name: Ensure chukonu jar exists on the remote
      ansible.builtin.copy:
        src: /opt/chukonu_install/jar/chukonu_2.12-0.5.1.jar
        dest: /opt/all_jars/
        remote_src: yes
      become: true