- name: Run TPC-DS benchmark script on master
  hosts: master
  become: yes
  tasks:
    - name: Execute TPC-DS benchmark script as root in /opt/tpcds-benchmark
      become: yes
      become_user: root
      shell: |
        cd /opt/tpcds-benchmark && ./run-spark.sh true true true true > result.log 2>&1
      register: tpcds_benchmark_output
      ignore_errors: yes
    - name: Print TPC-DS benchmark script output
      debug:
        var: tpcds_benchmark_output.stdout_lines