- name: Create systemd service for TPC-DS benchmark
  hosts: master  # 这里指定主节点
  become: yes  # 提升为 root 用户
  tasks:
    - name: Create systemd service file for TPC-DS benchmark
      copy:
        dest: /etc/systemd/system/tpcds-benchmark.service
        content: |
          [Unit]
          Description=TPC-DS Benchmark Service
          After=network.target

          [Service]
          Type=simple
          ExecStart=/opt/tpcds-benchmark/run-spark.sh true true true true
          Restart=on-failure
          User=root
          WorkingDirectory=/opt/tpcds-benchmark

          [Install]
          WantedBy=multi-user.target
      notify:
        - Restart TPC-DS benchmark service

    - name: Enable and start TPC-DS benchmark service
      systemd:
        name: tpcds-benchmark
        enabled: yes
        state: started

  handlers:
    - name: Restart TPC-DS benchmark service
      systemd:
        name: tpcds-benchmark
        state: restarted