- name: Mount NVMe disks and format if necessary
  hosts: all
  become: yes
  vars:
    driver_disk_cnt: 1  # 主节点的磁盘数量
    disk_cnt: 1         # 工作节点的磁盘数量
  tasks:
    - name: Format and mount NVMe disks for master node
      block:
        - name: Format and mount driver disk for master node
          block:
            - name: Format the NVMe disk to xfs
              filesystem:
                fstype: xfs
                dev: "/dev/nvme{{ item }}n1"
              loop: "{{ range(1, driver_disk_cnt + 1) | list }}"

            - name: Mount the last disk for Hadoop
              mount:
                path: "/opt"
                src: "/dev/nvme{{ driver_disk_cnt }}n1"
                fstype: xfs
                opts: defaults
                state: mounted
              when: driver_disk_cnt > 1
            - name: Mount other driver disks to /metadata
              mount:
                path: "/metadata{{ item }}"
                src: "/dev/nvme{{ item + 1 }}n1"
                fstype: xfs
                opts: defaults
                state: mounted
              loop: "{{ range(1, driver_disk_cnt + 1) | list }}"
              when: item < driver_disk_cnt or driver_disk_cnt <= 1
          when: "'master' in group_names"

        - name: Add mount entries to /etc/fstab for master node /metadata
          lineinfile:
            path: /etc/fstab
            line: "/dev/nvme{{ item }}n1 /metadata{{ item - 1  }} xfs defaults 0 0"
          loop: "{{ range(1, driver_disk_cnt) | list }}"
          when: 
            - "'master' in group_names"
            - item < driver_disk_cnt or driver_disk_cnt <= 1

        - name: Add mount entries to /etc/fstab for master node /opt
          lineinfile:
            path: /etc/fstab
            line: "/dev/nvme{{ driver_disk_cnt }}n1 /opt xfs defaults 0 0"
          when: 
            - "'master' in group_names"
            - driver_disk_cnt > 1
       

    - name: Format and mount NVMe disks for worker nodes
      block:
        - name: Format and mount driver disk for master node
          block:
            - name: Format the NVMe disk to xfs
              filesystem:
                fstype: xfs
                dev: "/dev/nvme{{ item }}n1"
              loop: "{{ range(1, driver_disk_cnt + 1) | list }}"

            - name: Mount the last disk for Hadoop
              mount:
                path: "/opt"
                src: "/dev/nvme{{ driver_disk_cnt }}n1"
                fstype: xfs
                opts: defaults
                state: mounted
              when: driver_disk_cnt > 1
            - name: Mount other driver disks to /data
              mount:
                path: "/data{{ item }}"
                src: "/dev/nvme{{ item + 1 }}n1"
                fstype: xfs
                opts: defaults
                state: mounted
              loop: "{{ range(1, driver_disk_cnt + 1) | list }}"
              when: item < driver_disk_cnt or driver_disk_cnt <= 1
          when: "'worker' in group_names"

        - name: Add mount entries to /etc/fstab for worker node /data
          lineinfile:
            path: /etc/fstab
            line: "/dev/nvme{{ item }}n1 /data{{ item - 1  }} xfs defaults 0 0"
          loop: "{{ range(1, driver_disk_cnt) | list }}"
          when: 
            - "'worker' in group_names"
            - item < driver_disk_cnt or driver_disk_cnt <= 1

        - name: Add mount entries to /etc/fstab for worker node /opt
          lineinfile:
            path: /etc/fstab
            line: "/dev/nvme{{ driver_disk_cnt }}n1 /opt xfs defaults 0 0"
          when: 
            - "'worker' in group_names"
            - driver_disk_cnt > 1