name: Deploy and Test Spark Cluster on AWS

on:
  push:
    branches:
      - feature/auto

jobs:
  checkout-and-deploy:
    uses: ./.github/workflows/deploy.yml

  setup-ssh:
    uses: ./.github/workflows/setup_ssh.yml

  install-dependencies:
    uses: ./.github/workflows/install_dependencies.yml

  run-tests:
    needs: install-dependencies
    uses: ./.github/workflows/run_tests.yml

  terminate-instances:
    if: always()
    needs: run-tests
    uses: ./.github/workflows/terminate_instances.yml